# Generated by Django 6.0.1 on 2026-01-13 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(max_length=200, verbose_name='Название образца')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год реализации')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь (м²)')),
                ('client_type', models.CharField(blank=True, max_length=200, verbose_name='Тип объекта/Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_info', models.CharField(blank=True, max_length=200, verbose_name='Информация о стоимости')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='samples/pdfs/', verbose_name='PDF файл-пример')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Образец проекта',
                'verbose_name_plural': 'Образцы проектов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('image', models.ImageField(upload_to='samples/images/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samples.sample', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'Изображение образца',
                'verbose_name_plural': 'Изображения образцов',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
