# Generated by Django 6.0.1 on 2026-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Описание для поисковых систем (до 160 символов)', max_length=160, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='sample',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta ключевые слова'),
        ),
    ]
