# Generated by Django 6.0 on 2026-01-05 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(help_text='Заголовок страницы', max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Уникальный URL-адрес страницы', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(help_text='Основное содержимое страницы', verbose_name='Содержимое')),
                ('meta_description', models.CharField(blank=True, help_text='Описание для поисковых систем (до 160 символов)', max_length=160, verbose_name='Meta описание')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta ключевые слова')),
                ('is_published', models.BooleanField(default=False, help_text='Отображать страницу на сайте', verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения в меню', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='pages_page_slug_3e99a9_idx'), models.Index(fields=['is_published', 'order'], name='pages_page_is_publ_a6710f_idx')],
            },
        ),
    ]
