# Generated by Django 6.0 on 2026-01-07 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('client_name', models.CharField(help_text='Имя клиента', max_length=100, verbose_name='Имя клиента')),
                ('client_info', models.CharField(blank=True, help_text='Например: ЖК Символ, 100 м²', max_length=200, verbose_name='Информация о проекте')),
                ('text', models.TextField(help_text='Текст отзыва', verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Оценка от 1 до 5', verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=True, help_text='Отображать отзыв на сайте', verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
