# Generated by Django 6.0.1 on 2026-01-09 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(help_text='Например: ТЕХНИЧЕСКИЙ ПРОЕКТ', max_length=255, verbose_name='Название услуги')),
                ('price', models.CharField(help_text='Например: от 5 долл/мкв', max_length=100, verbose_name='Цена')),
                ('steps_text', models.TextField(help_text='Введите каждый этап с новой строки. Они будут разделены стрелочками.', verbose_name='Этапы работы')),
                ('composition_text', models.TextField(help_text='Введите каждый пункт с новой строки. Первые 4 будут видны сразу, остальные — при раскрытии.', verbose_name='Состав документации')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF файл для кнопки "Образец проекта"', null=True, upload_to='prices/pdfs/', verbose_name='Файл примера (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга и цена',
                'verbose_name_plural': 'Услуги и цены',
                'ordering': ['order', 'title'],
            },
        ),
    ]
