# Generated by Django 6.0.1 on 2026-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_priceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Превью для страницы "Образцы проектов"', null=True, upload_to='prices/images/', verbose_name='Изображение для образца'),
        ),
        migrations.AddField(
            model_name='priceservice',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальная метка для URL (например: technicheskiy-proekt). Если не заполнено, будет создано автоматически.', max_length=100, null=True, unique=True, verbose_name='URL-метка'),
        ),
    ]
