# Generated by Django 6.0 on 2026-01-05 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Название категории', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный URL-адрес категории', max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Описание категории', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(help_text='Название проекта', max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(help_text='Уникальный URL-адрес проекта', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('year', models.IntegerField(help_text='Год реализации проекта', verbose_name='Год реализации')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Площадь объекта в квадратных метрах', max_digits=10, null=True, verbose_name='Площадь (м²)')),
                ('description', models.TextField(help_text='Подробное описание проекта', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для превью', max_length=500, verbose_name='Краткое описание')),
                ('client_type', models.CharField(blank=True, help_text='Например: для семейной пары, для молодой семьи', max_length=200, verbose_name='Тип клиента')),
                ('is_published', models.BooleanField(default=False, help_text='Отображать проект на сайте', verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать в избранных проектах', verbose_name='Избранное')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('meta_description', models.CharField(blank=True, help_text='Описание для поисковых систем', max_length=160, verbose_name='Meta описание')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Meta ключевые слова')),
                ('category', models.ForeignKey(blank=True, help_text='Категория проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-is_featured', 'order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCharacteristic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(help_text='Название характеристики', max_length=100, verbose_name='Название')),
                ('value', models.CharField(help_text='Значение характеристики', max_length=200, verbose_name='Значение')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('project', models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='portfolio.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Характеристика проекта',
                'verbose_name_plural': 'Характеристики проектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметка об удалении записи', verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата и время удаления записи', null=True, verbose_name='Дата удаления')),
                ('image', models.ImageField(help_text='Изображение проекта', upload_to='portfolio/%Y/%m/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, help_text='Название изображения', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание изображения', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения в галерее', verbose_name='Порядок')),
                ('is_cover', models.BooleanField(default=False, help_text='Использовать как обложку проекта', verbose_name='Обложка')),
                ('project', models.ForeignKey(help_text='Проект, к которому относится изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проектов',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'is_featured'], name='portfolio_p_is_publ_674f93_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['year'], name='portfolio_p_year_7d194d_idx'),
        ),
    ]
